name: northstar-testing
type: wordpress
docroot: ""
php_version: "8.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
database:
  type: mariadb
  version: "10.6"
nodejs_version: "20"
